# 项目相关配置
ruoyi:
  # 名称
  name: 问卷调查
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2023
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/ruoyi/uploadPath
  #  profile: /home/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math
    # appId和secret要换成自己的
    # 微信小程序的appId
#  appId: wxd4620cfa7d04cff1
  # 微信小程序的secret
#  secret: 2246cb339865526c1fd71f2dae525f3b

  appId: wxf5752db94f663dce
#  # 微信小程序的secret
  secret: bc595aef2d8612b036b41bffe93d53a8


# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
  address: 0.0.0.0

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

mso:
  products:
    service:
      impl: com.maintain.service.MsoProductsServiceImpl

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    #    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  cache:
    type: redis
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  # 添加了 积分参数和分销参数 的排除
  excludes: /system/notice,/system/value,/system/param
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

  #jodconverter配置
  jodconverter:
    local:
      enabled: true
      #home安装地址
      #本地运行
      office-home: C:\\Program Files (x86)\\OpenOffice 4
      #云端部署
      #      office-home:  /opt/openoffice4
      max-tasks-per-process: 10
      port-numbers: 8100

url:
  httpUrl: https://gkxiu.com/profile/


# 微信小程序消息模板
wechat:
  template:
    templateId:
      #确认报价
      confirmQuotation: pwNI0GHLqZPdJTA5nWKHf-nxBUhWC0P10pbW5LfO4Pw
      #维修完成
      repairCompleted: CejkLqOmno38QkM_ymmwW6JGgYCgoqxfCRa5FWiHtxc
      #拜访客户
      visitClient: Wc3cfh3JQwUA4niurZXGWP1rKKiiUhnzxi34ajAc13k

    param:
      #确认报价
      confirmQuotation: character_string1/thing7/amount3/thing9
      #维修完成
      repairCompleted: character_string7/thing9/amount8
      #拜访客户
      visitClient: thing5/thing7/time6/thing3

    page:
      confirmQuotation: /pages/componentsA/repair/repair
      repairCompleted: /pages/componentsA/delivery/delivery
      visitClient: /pages/componentsB/visit/index

